name: smart_route
description: "A new Flutter project."

publish_to: "none" 
version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  equatable: ^2.0.5
  flutter_bloc: ^8.1.5
  get_it: ^7.6.7
  go_router: ^13.2.2
  just_audio: ^0.9.37
  just_audio_background: ^0.0.1-beta.11
  on_audio_query: ^2.9.0
  permission_handler: ^11.3.1
  dio: ^5.4.2+1
  flutter_svg: ^2.0.10+1
  flutter_osm_plugin: ^1.0.0-rc.6
  location: ^6.0.0
  http: ^1.2.1
  open_street_map_search_and_pick: ^0.1.1
  url_launcher: ^6.2.6
 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

  flutter_lints: ^3.0.2

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/logo.png"
  # adaptive_icon_foreground: "assets/icons/logo_foreground.png"
  # adaptive_icon_background: "#ffffff"
  remove_alpha_ios: true
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  uses-material-design: true

  assets:
    - assets/
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
